### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by mrenvoize**
Fixing version numbers

### CODE REVIEW

**Comment by mrenvoize** [comment]
I was finding I couldn't get CPAN to recognise the new release as the latest version and eventually I think I pinned it down to being a version number issue.

``` perl
perl -Mversion -e'print version->parse("2.010") < version->parse("2.09");
```

Yields true, so I don't think cpan will ever attempt to install 2.010.

**Comment by briandfoy** [comment]
I'm deleting the old distributions from PAUSE and want to try to reindex it first. It takes a couple of days for that to take effect.

**Comment by mrenvoize** [comment]
Thanks @briandfoy, I never realised how hard perl versioning could be.. took me a while to get my head around why things weren't working.

Hope you have a great Christmas, these aren't urgent to me.. just nice to clean ups.

**Comment by briandfoy** [comment]
The distro is re-indexed. You may have to delete the old version already installed or do a force install.

**Comment by mrenvoize** [comment]
Excellent, all appears to work well now from this end :).

I have no idea how you got it to work with the existing version numbering, but I'm glad you could.

I'll make a mental note to read up further on versioning modules as I obviously missed something.

Many thanks, have a great Christmas,

**Comment by eserte** [comment]
> I'm deleting the old distributions from PAUSE and want to try to reindex it first. It takes a couple of days for that to take effect. 

This would "fix" PAUSE, but not other systems (e.g. the version list on matrix.cpantesters.org will still look wrong, or upstream packagers have now to play version tricks). Also, somebody who has 2.09 already installed on his system won't be able to update with CPAN.pm without doing tricks.

Applying this pull request is still the best solution, IMHO.

**Pull request closed without merging**
